apiVersion: v1
kind: Service
metadata:
  name: spark-master  
  labels:
    name: spark-master
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - name: dashboard
    port: 5234
    targetPort: 5234
  selector:
    name: spark-master  