apiVersion: v1
kind: Service
metadata:
  name: spark-master  
  labels:
    name: spark-master
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - name: webui
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: spark
    port: 7077
    targetPort: 7077
    nodePort: 30077
  - name: driverui
    port: 4040
    targetPort: 4040
    nodePort: 30040
  - name: hdfs
    port: 9000
    targetPort: 9000
    nodePort: 30090
  - name: dfshealth
    port: 50070
    targetPort: 50070
    nodePort: 30070
  - name: dashboard
    port: 5234
    targetPort: 5234
    nodePort: 30052
  selector:
    name: spark-master