apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-master
  name: spark-master  
spec:
  replicas: 1
  selector:
    name: spark-master
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - image: cacidocker-caciuk.azurecr.io/caci-main/spark-master
        name: spark-master       
        resources:
          requests:   
            memory: 10Gi
          limits:
            memory: 16Gi       
        volumeMounts:
          - mountPath: /root/hdfs/datanode
            name: hdfs-dir
          - mountPath: /root/hdfs/namenode
            name: hdfs-dir
          - mountPath: /root/hdfs/tmp
            name: hdfs-dir
          - mountPath: /root/hdfs/spark-warehouse
            name: hdfs-dir
          - mountPath: /data
            name: data-dir
        command: ["/bin/sh"]
        args: ["-c", "chmod 777 /run.sh; /run.sh"]    
        env:
          - name: FORMAT_HDFS
            value: "false"
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - containerPort: 7077
          hostPort: 7077
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 50070
          hostPort: 50070
          protocol: TCP      
      nodeSelector:
        master: "true"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
      - name: hdfs-dir  
        hostPath:
          path: /grid/hdfs/
      - name: data-dir  
        hostPath:
          path: /data/