apiVersion: v1
kind: Service
metadata:
  name: spark-master  
  labels:
    name: spark-master
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - name: webui
    port: 8080
    targetPort: 30080
  - name: spark
    port: 7077
    targetPort: 30077
  - name: driverui
    port: 4040
    targetPort: 30040
  - name: hdfs
    port: 9000
    targetPort: 30090
  - name: dfshealth
    port: 50070
    targetPort: 30070
  selector:
    name: spark-master  