apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-worker
  name: spark-worker  
spec:
  replicas: 2
  selector:
    name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: cacidocker-caciuk.azurecr.io/caci-main/spark-worker
        name: spark-worker   
        volumeMounts:
          - mountPath: /root/hdfs/datanode
            name: ssd0         
        resources:
            requests:                    
              memory: 6Gi
            limits:
              memory: 8Gi
        env:
        - name: SPARK_WORKER_MEMORY
          value: 8g                              
        ports:
        - containerPort: 7078
          hostPort: 7078
          protocol: TCP
        - containerPort: 50010
          hostPort: 50010
          protocol: TCP
        - containerPort: 50020
          hostPort: 50020
          protocol: TCP      
      imagePullSecrets:
        - name: myregistrykey
      volumes:
      - name: ssd0 
        hostPath:
          path: /grid