apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-worker
  name: spark-worker  
spec:
  replicas: 3
  selector:
    name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: cacidocker-caciuk.azurecr.io/caci-main/spark-worker
        name: spark-worker           
        resources:
            requests:                    
              memory: 1Gi
            limits:
              memory: 2Gi                            
        ports:
        - containerPort: 7078
          hostPort: 7078
          protocol: TCP
        - containerPort: 50010
          hostPort: 50010
          protocol: TCP
        - containerPort: 50020
          hostPort: 50020
          protocol: TCP      
      imagePullSecrets:
        - name: myregistrykey